/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
*/

import {useAnimations, useFBX, useGLTF} from "@react-three/drei";
import {useFrame, useLoader} from "@react-three/fiber";
import {useControls} from "leva";
import React, {useEffect, useMemo, useRef, useState} from "react";

import * as THREE from "three";

// mapping of letters to morph target names used for rhubarb lipsyncing
const corresponding = {
    A: "viseme_PP",
    B: "viseme_kk",
    C: "viseme_I",
    D: "viseme_AA",
    E: "viseme_O",
    F: "viseme_U",
    G: "viseme_FF",
    H: "viseme_TH",
    X: "viseme_PP",
};

// avatar component defn
export function Avatar(props) {

    // state vars and controls
    const {
        playAudio,
        script,
        headFollow,
        smoothMorphTarget,
        morphTargetSmoothing,
    } = useControls({
        playAudio: false,
        headFollow: true,
        smoothMorphTarget: true,
        morphTargetSmoothing: 0.5,
        script: {
            value: "welcome",
            options: ["welcome", "pizzas"],
        },
    });

    // load audio and lipsync data based on script
    const audio = useMemo(() => new Audio(`/audios/${script}.mp3`), [script]);
    const jsonFile = useLoader(THREE.FileLoader, `audios/${script}.json`);
    const lipsync = JSON.parse(jsonFile);

    //
    useFrame(() => {
        const currentAudioTime = audio.currentTime;
        // if (audio.paused || audio.ended) {
        //   setAnimation("Idle");
        //   return;
        // }

        Object.values(corresponding).forEach((value) => {
            // Set morph targets to 0 if smoothing is disabled
            if (!smoothMorphTarget) {
                nodes.Wolf3D_Head.morphTargetInfluences[
                    nodes.Wolf3D_Head.morphTargetDictionary[value]
                    ] = 0;
                nodes.Wolf3D_Teeth.morphTargetInfluences[
                    nodes.Wolf3D_Teeth.morphTargetDictionary[value]
                    ] = 0;
            } else {
                // Smoothly interpolate morph targets if smoothing is enabled
                nodes.Wolf3D_Head.morphTargetInfluences[
                    nodes.Wolf3D_Head.morphTargetDictionary[value]
                    ] = THREE.MathUtils.lerp(
                    nodes.Wolf3D_Head.morphTargetInfluences[
                        nodes.Wolf3D_Head.morphTargetDictionary[value]
                        ],
                    0,
                    morphTargetSmoothing
                );

                nodes.Wolf3D_Teeth.morphTargetInfluences[
                    nodes.Wolf3D_Teeth.morphTargetDictionary[value]
                    ] = THREE.MathUtils.lerp(
                    nodes.Wolf3D_Teeth.morphTargetInfluences[
                        nodes.Wolf3D_Teeth.morphTargetDictionary[value]
                        ],
                    0,
                    morphTargetSmoothing
                );
            }
        });

        for (let i = 0; i < lipsync.mouthCues.length; i++) {
            const mouthCue = lipsync.mouthCues[i];
            if (
                currentAudioTime >= mouthCue.start &&
                currentAudioTime <= mouthCue.end
            ) {
                if (!smoothMorphTarget) {
                    nodes.Wolf3D_Head.morphTargetInfluences[
                        nodes.Wolf3D_Head.morphTargetDictionary[
                            corresponding[mouthCue.value]
                            ]
                        ] = 1;
                    nodes.Wolf3D_Teeth.morphTargetInfluences[
                        nodes.Wolf3D_Teeth.morphTargetDictionary[
                            corresponding[mouthCue.value]
                            ]
                        ] = 1;
                } else {
                    nodes.Wolf3D_Head.morphTargetInfluences[
                        nodes.Wolf3D_Head.morphTargetDictionary[
                            corresponding[mouthCue.value]
                            ]
                        ] = THREE.MathUtils.lerp(
                        nodes.Wolf3D_Head.morphTargetInfluences[
                            nodes.Wolf3D_Head.morphTargetDictionary[
                                corresponding[mouthCue.value]
                                ]
                            ],
                        1,
                        morphTargetSmoothing
                    );
                    nodes.Wolf3D_Teeth.morphTargetInfluences[
                        nodes.Wolf3D_Teeth.morphTargetDictionary[
                            corresponding[mouthCue.value]
                            ]
                        ] = THREE.MathUtils.lerp(
                        nodes.Wolf3D_Teeth.morphTargetInfluences[
                            nodes.Wolf3D_Teeth.morphTargetDictionary[
                                corresponding[mouthCue.value]
                                ]
                            ],
                        1,
                        morphTargetSmoothing
                    );
                }

                break;
            }
        }
    });

    useEffect(() => {
        nodes.Wolf3D_Head.morphTargetInfluences[
            nodes.Wolf3D_Head.morphTargetDictionary["viseme_I"]
            ] = 1;
        nodes.Wolf3D_Teeth.morphTargetInfluences[
            nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_I"]
            ] = 1;
        if (playAudio) {
            audio.play();
            // if (script === "welcome") {
            //   setAnimation("Greeting");
            // } else {
            //   setAnimation("Angry");
            // }
        } else {
            // setAnimation("Idle");
            audio.pause();
        }
    }, [playAudio, script]);

    // load avatar model and animations
    const {nodes, materials} = useGLTF("models/646d9dcdc8a5f5bddbfac913.glb");
    // const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
    // const { animations: angryAnimation } = useFBX(
    //   "/animations/Angry Gesture.fbx"
    // );
    // const { animations: greetingAnimation } = useFBX(
    //   "/animations/Standing Greeting.fbx"
    // );


    // set animation names
    // idleAnimation[0].name = "Idle";
    // angryAnimation[0].name = "Angry";
    // greetingAnimation[0].name = "Greeting";

    // define animation state and actions
    // const [animation, setAnimation] = useState("Idle");
    const group = useRef();
    // const { actions } = useAnimations(
    //   [idleAnimation[0], angryAnimation[0], greetingAnimation[0]],
    //   group
    // );

    // useEffect(() => {
    //   actions[animation].reset().fadeIn(0.5).play();
    //   return () => actions[animation].fadeOut(0.5);
    // }, [animation]);

    // head follow
    useFrame((state) => {
        if (headFollow) {
            group.current.getObjectByName("Head").lookAt(state.camera.position);
        }
    });

    // RightFoot
    useEffect(() => {
        const RF = group.current.getObjectByName("RightFoot");
        if (RF) {
            const targetRotation = new THREE.Quaternion();
            targetRotation.setFromAxisAngle(new THREE.Vector3(0, 1, 0), Math.PI / 2);
            RF.quaternion.copy(targetRotation);
        }
        console.log(nodes);
    }, []);

    // RightArm
    useEffect(() => {
        const RA = group.current.getObjectByName("RightArm");
        if (RA) {
            const targetRotation = new THREE.Quaternion();
            targetRotation.setFromAxisAngle(new THREE.Vector3(-1, 0, 0), Math.PI / 4);
            RA.quaternion.copy(targetRotation);
        }
    }, []);

    // LeftArm
    useEffect(() => {
        const leftArm = group.current.getObjectByName("LeftArm");
        if (leftArm) {
            const targetRotation = new THREE.Quaternion();
            targetRotation.setFromAxisAngle(new THREE.Vector3(0, 1, 0), 1);
            leftArm.quaternion.copy(targetRotation);
        }
    }, []);

    return (
        <group {...props} dispose={null} ref={group}>
            <primitive object={nodes.Hips}/>
            <skinnedMesh
                geometry={nodes.Wolf3D_Body.geometry}
                material={materials.Wolf3D_Body}
                skeleton={nodes.Wolf3D_Body.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                material={materials.Wolf3D_Outfit_Bottom}
                skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                material={materials.Wolf3D_Outfit_Footwear}
                skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Outfit_Top.geometry}
                material={materials.Wolf3D_Outfit_Top}
                skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Hair.geometry}
                material={materials.Wolf3D_Hair}
                skeleton={nodes.Wolf3D_Hair.skeleton}
            />
            <skinnedMesh
                name="EyeLeft"
                geometry={nodes.EyeLeft.geometry}
                material={materials.Wolf3D_Eye}
                skeleton={nodes.EyeLeft.skeleton}
                morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            />
            <skinnedMesh
                name="EyeRight"
                geometry={nodes.EyeRight.geometry}
                material={materials.Wolf3D_Eye}
                skeleton={nodes.EyeRight.skeleton}
                morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Head"
                geometry={nodes.Wolf3D_Head.geometry}
                material={materials.Wolf3D_Skin}
                skeleton={nodes.Wolf3D_Head.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Teeth"
                geometry={nodes.Wolf3D_Teeth.geometry}
                material={materials.Wolf3D_Teeth}
                skeleton={nodes.Wolf3D_Teeth.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            />
        </group>
    );
}

useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");
