/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/65f86d86553ebe525eb5e280.glb -o src/components/Avatar.jsx -r public
*/

import {useAnimations, useFBX, useGLTF} from "@react-three/drei";
import {useFrame, useLoader} from "@react-three/fiber";
import {useControls} from "leva";
import React, {useEffect, useMemo, useRef, useState} from "react";
import {editable as e, SheetProvider} from "@theatre/r3f";
import {getProject} from '@theatre/core'

import * as THREE from "three";


export function AudiolessAvatar(props) {

    const {glbEndpoint} = props

    const {nodes, materials} = useGLTF(glbEndpoint)


    return (
        <e.group theatreKey="avatarNoSound" {...props} dispose={null}>
            <primitive object={nodes.Hips}/>

            {nodes.Wolf3D_Body && (
                <skinnedMesh
                    geometry={nodes.Wolf3D_Body.geometry}
                    material={materials.Wolf3D_Body}
                    skeleton={nodes.Wolf3D_Body.skeleton}
                />
            )}

            {nodes.Wolf3D_Outfit_Bottom && (
                <skinnedMesh
                    geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                    material={materials.Wolf3D_Outfit_Bottom}
                    skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                />
            )}

            {nodes.Wolf3D_Outfit_Footwear && (
                <skinnedMesh
                    geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                    material={materials.Wolf3D_Outfit_Footwear}
                    skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                />
            )}

            {nodes.Wolf3D_Outfit_Top && (
                <skinnedMesh
                    geometry={nodes.Wolf3D_Outfit_Top.geometry}
                    material={materials.Wolf3D_Outfit_Top}
                    skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                />
            )}

            {nodes.Wolf3D_Hair && (
                <skinnedMesh
                    geometry={nodes.Wolf3D_Hair.geometry}
                    material={materials.Wolf3D_Hair}
                    skeleton={nodes.Wolf3D_Hair.skeleton}
                />
            )}

            {nodes.EyeLeft && (
                <skinnedMesh
                    name="EyeLeft"
                    geometry={nodes.EyeLeft.geometry}
                    material={materials.Wolf3D_Eye}
                    skeleton={nodes.EyeLeft.skeleton}
                    morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                    morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
                />
            )}

            {nodes.EyeRight && (
                <skinnedMesh
                    name="EyeRight"
                    geometry={nodes.EyeRight.geometry}
                    material={materials.Wolf3D_Eye}
                    skeleton={nodes.EyeRight.skeleton}
                    morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                    morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
                />
            )}

            {nodes.Wolf3D_Head && (
                <skinnedMesh
                    name="Wolf3D_Head"
                    geometry={nodes.Wolf3D_Head.geometry}
                    material={materials.Wolf3D_Skin}
                    skeleton={nodes.Wolf3D_Head.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
                />
            )}

            {nodes.Wolf3D_Teeth && (
                <skinnedMesh
                    name="Wolf3D_Teeth"
                    geometry={nodes.Wolf3D_Teeth.geometry}
                    material={materials.Wolf3D_Teeth}
                    skeleton={nodes.Wolf3D_Teeth.skeleton}
                    morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                    morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
                />
            )}
        </e.group>
    );

}

useGLTF.preload("http://localhost:5050/avatars/65f86d86553ebe525eb5e280.glb");
